services:
  go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
    #      - NETWORK_PROXY_SERVER=http://host:port
    #      - NETWORK_PROXY_SERVER=socks5://host:port
    restart: unless-stopped
